### ISSUE TITLE
upkeep: `create_benchmark_loanbook()` cannot use `code_level` from `r2dii.data` anymore

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.multi.loanbook.analysis#18]
`code_level` is deprecated in sector classifications in https://github.com/RMI-PACTA/r2dii.data/pull/352

use an alternative

fyi @jdhoffa 

AB#10277

**Comment by jdhoffa** [comment]
Interesting, how is this value used in the current system? Is this a reason that we should continue to export this column?

**Comment by jacobvjk** [comment]
It's not strictly needed, but I am using it to get a NACE code for each sector in the "benchmark loan book" that I know will match an in-scope sector.
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/blob/1fb6448e109ebec3202efe6ac6b2c61ab43a931f/R/create_benchmark_loanbook.R#L39

So basically it is used to filter the the `nace_classification` to only `borderline == FALSE` and maximum code depth and then I just pick the first code for each sector. technically, we do not need to use the lowest level of granularity here though. I just preferred it because the lowest level usually maps to the in-scope sectors best.

**Comment by jacobvjk** [comment]
it is also used in `sample_raw_loanbook_from_abcd()` in the workflow though. Will add a similar ticket there

**Comment by jdhoffa** [comment]
> It's not strictly needed, but I am using it to get a NACE code for each sector in the "benchmark loan book" that I know will match an in-scope sector.
> 
> https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/blob/1fb6448e109ebec3202efe6ac6b2c61ab43a931f/R/create_benchmark_loanbook.R#L39
> 
> So basically it is used to filter the the `nace_classification` to only `borderline == FALSE` and maximum code depth and then I just pick the first code for each sector. technically, we do not need to use the lowest level of granularity here though. I just preferred it because the lowest level usually maps to the in-scope sectors best.

In that case, you could probably also just use `max(nchar(code))` to get the "most specific" code.
