### ISSUE TITLE
upkeep: maybe rename `.github/workflows/R.yml` to `R-CMD-check.yaml`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.multi.loanbook.analysis#30]
This seems to be what the default R CMD check bade (that `usethis` creates) is expected. 

This is why the badge isn't rendering here: 
<img width="473" alt="Screenshot 2024-04-03 at 18 09 22" src="https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/assets/8741309/938e593f-da63-4c71-9cad-2dcc95bb9958">

(Alternatively can change the link to point to `R.yml`, but i'd prefer the former option as it aligns with what 99% of our other repos already do). 

cc: @AlexAxthelm 

Relates to https://github.com/RMI-PACTA/pacta.sit.rep/pull/18

**Comment by AlexAxthelm** [comment]
@jdhoffa since `R.yml` does a fair bit more than `R CMD CHECK`, maybe we should align on a better name along the lines of `R Package Checks`?

**Comment by jdhoffa** [comment]
I'm going to close this issue, since it doesn't really belong in this repo. 

Seems like more an @AlexAxthelm and me discussion!
