### ISSUE TITLE
upkeep: pkgdown website does not build - fix

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.multi.loanbook.analysis#31]
I believe there was a general issue related to how we used pkgdown, is that correct? do we know how to fix it?

@jdhoffa @cjyetman 

AB#10482

**Comment by jdhoffa** [comment]
This box had to be checked in the "Settings" of this repo:

<img width="359" alt="Screenshot 2024-04-04 at 09 57 06" src="https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/assets/8741309/95456224-f109-4afb-b355-548165a870ac">

**Comment by jdhoffa** [comment]
https://rmi-pacta.github.io/pacta.multi.loanbook.analysis/

Closing this issue :-)
