### ISSUE TITLE
feat: use column name `id_loanbook` instead of `group_id`

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.multi.loanbook.analysis#35]
relates to #33 

previously we used the column `group_id` to identify one variable by which to analyze/aggregate loan books. This is not ideal for the following reasons:

- users will normally always prepare data by loan book, so it is safe to assume that it is always possible to attribute an identifier to each loan book
- when analyzing the financial system, there is rarely a situation where we do not care about the individual loan book view
- `group_id` does not follow the naming conventions that other id variables in P4B use. It is normally `id_*` not `*_id`
- We still want to be able to analyze/aggregate the data by other dimensions, which we do by passing column names to the new `group_var` argument (see linked issue). This means that clearer disambiguation of names would be helpful.

AB#10594

**Comment by jdhoffa** [comment]
I have some comments on this architecturally...

Given past experience, I think it would be vastly preferable to have a base function that expects the single unitary data-frame required and calculates whatever it needs to off that data-frame, and then, write a wrapper around that function that allows a data-frame with arbitrary col-names and input groups...

basically mimicking the `group_by` semantics as much as possible, and not introducing any new `group_var` or `group_id` concept... let me know if you want to discuss. 

the result is something that is overall more flexible

**Comment by jacobvjk** [comment]
> I have some comments on this architecturally...
> 
> Given past experience, I think it would be vastly preferable to have a base function that expects the single unitary data-frame required and calculates whatever it needs to off that data-frame, and then, write a wrapper around that function that allows a data-frame with arbitrary col-names and input groups...
> 
> basically mimicking the `group_by` semantics as much as possible, and not introducing any new `group_var` or `group_id` concept... let me know if you want to discuss.
> 
> the result is something that is overall more flexible

Hard coded grouping variables are indeed being dropped
