### ISSUE TITLE
Build NOTE: no visible binding for global variable

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.multi.loanbook.analysis#6]
copies: https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/issues/101

`no visible binding for global variable` for variables in `fill_missing_direction()`

**Comment by jacobvjk** [comment]
I have not been able to figure out how to get rid of the `NOTE` relating to function `fill_missing_direction()`. Any attempt I have made at fixing the `no visible binding for global variable` issue in two nested `tidyr` functions has lead to ERRORs in R CMD... any ideas?

**Comment by jdhoffa** [comment]
Wanna schedule a pair program with me on Thursday? Need a bit more context to help 😊

**Comment by cjyetman** [comment]
using `group_id <- name_abcd <- sector <- activity_unit <- region <- scenario_source <- scenario <- year <- NULL` inside the function `fill_missing_direction()` is one hack to get around the build notes (see https://github.com/tidyverse/tidyr/issues/971#issuecomment-1912947368)

the other is to add these to `imports.R` (see https://github.com/tidyverse/tidyr/issues/971#issuecomment-1912862056)
```r
utils::globalVariables("group_id")
utils::globalVariables("name_abcd")
utils::globalVariables("sector")
utils::globalVariables("activity_unit")
utils::globalVariables("region")
utils::globalVariables("scenario_source")
utils::globalVariables("scenario")
utils::globalVariables("year")
```

seems like these will be the only options until tidyverse figures out and implements a very different strategy (see https://github.com/tidyverse/tidyr/issues/971#issuecomment-985671947)

**Comment by jacobvjk** [comment]
I don't really love either, but would probably lean towards the first option as it seems like it does not play with global variables across the entire package for no reason.

**Comment by AlexAxthelm** [comment]
I know I'm late to the party here, but is there a reason to not use quoted strings, rather than bare column names?
